In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
bankdata=pd.read_csv("E:/machine learning software/Datasets BITS/bank-full.csv")

In [5]:
bankdata.dtypes

age           int64
job          object
marital      object
education    object
default      object
balance       int64
housing      object
loan         object
contact      object
day           int64
month        object
duration      int64
campaign      int64
pdays         int64
previous      int64
poutcome     object
y            object
dtype: object

In [6]:
bankdatacat=bankdata.select_dtypes(include=['object'])
bankdatanum=bankdata.select_dtypes(include=[np.number])

In [7]:
bankdatacat.head()

job  marital  education default housing loan  contact month  \
0    management  married   tertiary      no     yes   no  unknown   may   
1    technician   single  secondary      no     yes   no  unknown   may   
2  entrepreneur  married  secondary      no     yes  yes  unknown   may   
3   blue-collar  married    unknown      no     yes   no  unknown   may   
4       unknown   single    unknown      no      no   no  unknown   may   

  poutcome   y  
0  unknown  no  
1  unknown  no  
2  unknown  no  
3  unknown  no  
4  unknown  no

In [8]:
bankdata.isnull().sum().sort_values(ascending=False)

y            0
loan         0
job          0
marital      0
education    0
default      0
balance      0
housing      0
contact      0
poutcome     0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
age          0
dtype: int64

In [9]:
bankdatanum.head()

age  balance  day  duration  campaign  pdays  previous
0   58     2143    5       261         1     -1         0
1   44       29    5       151         1     -1         0
2   33        2    5        76         1     -1         0
3   47     1506    5        92         1     -1         0
4   33        1    5       198         1     -1         0

In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
le=LabelEncoder()

In [12]:
bankdatacat1=bankdatacat.apply(le.fit_transform)

In [13]:
bankdatacat1.head()

job  marital  education  default  housing  loan  contact  month  poutcome  \
0    4        1          2        0        1     0        2      8         3   
1    9        2          1        0        1     0        2      8         3   
2    2        1          1        0        1     1        2      8         3   
3    1        1          3        0        1     0        2      8         3   
4   11        2          3        0        0     0        2      8         3   

   y  
0  0  
1  0  
2  0  
3  0  
4  0

In [14]:
bankdatadf=pd.concat([bankdatacat1,bankdatanum],axis=1)

In [15]:
bankdatadf.head()

job  marital  education  default  housing  loan  contact  month  poutcome  \
0    4        1          2        0        1     0        2      8         3   
1    9        2          1        0        1     0        2      8         3   
2    2        1          1        0        1     1        2      8         3   
3    1        1          3        0        1     0        2      8         3   
4   11        2          3        0        0     0        2      8         3   

   y  age  balance  day  duration  campaign  pdays  previous  
0  0   58     2143    5       261         1     -1         0  
1  0   44       29    5       151         1     -1         0  
2  0   33        2    5        76         1     -1         0  
3  0   47     1506    5        92         1     -1         0  
4  0   33        1    5       198         1     -1         0

In [16]:
y=bankdatadf.y
X=bankdatadf.drop('y',axis=1)

In [17]:
from sklearn.linear_model import LinearRegression

In [18]:
LinReg=LinearRegression()

In [19]:
LinRegmodel=LinReg.fit(X,y)

In [20]:
LinRegmodel.score(X,y)

0.21116312879406451

In [21]:
LinRegmodel.intercept_

-0.1188508479497976

In [22]:
LinRegmodel.coef_

array([  1.01043558e-03,   1.88723138e-02,   1.65753426e-02,
        -2.17253080e-02,  -8.48610310e-02,  -4.43158520e-02,
        -3.87198865e-02,   5.01597261e-03,   2.85656478e-02,
         7.78209385e-04,   2.26879515e-06,  -3.91819716e-04,
         4.83599828e-04,  -2.96799156e-03,   4.39644002e-04,
         8.03046066e-03])

In [23]:
LinRegpredict=LinRegmodel.predict(X)

In [24]:
LinRegpredict

array([ 0.07158881,  0.01005081, -0.10510195, ...,  0.72142327,
        0.28229771,  0.36083218])

In [25]:
residual=y-LinRegpredict

In [26]:
residual

0       -0.071589
1       -0.010051
2        0.105102
3        0.006601
4       -0.144189
5        0.009647
6        0.002327
7       -0.069210
8        0.067179
9        0.035873
10       0.004240
11       0.016668
12      -0.175128
13       0.003369
14      -0.010699
15      -0.074150
16      -0.009219
17       0.077958
18      -0.015968
19       0.066378
20       0.018418
21      -0.020029
22       0.063924
23      -0.066787
24       0.062425
25       0.008670
26      -0.088318
27       0.065401
28      -0.053258
29      -0.055314
           ...   
45181   -0.114098
45182    0.640797
45183   -0.189853
45184   -0.183667
45185    0.825940
45186   -0.243278
45187    0.794843
45188    0.656155
45189   -0.162618
45190    0.757778
45191    0.847404
45192    0.783349
45193    0.665906
45194   -0.087912
45195    0.696875
45196    0.755428
45197    0.862171
45198   -0.248482
45199   -0.833215
45200    0.263593
45201    0.705262
45202    0.807710
45203    0.772307
45204    0.752651
45205    0

In [27]:
np.sqrt(np.mean(residual**2))

0.28545813003451209

LOGISTIC REGRESSION

In [29]:
from sklearn.linear_model import LogisticRegression

In [30]:
LogReg=LogisticRegression()

In [31]:
LogRegmodel=LogReg.fit(X,y)

In [32]:
LogRegmodel.score(X,y)

0.89069031872774329

In [33]:
LogRegpredict=LogRegmodel.predict(X)

In [34]:
LogRegpredict

array([0, 0, 0, ..., 1, 0, 1], dtype=int64)

In [35]:
pd.crosstab(bankdatadf.y,LogRegpredict)

col_0      0     1
y                 
0      39140   782
1       4160  1129

In [71]:
(39140+1129)/(39140+1129+4160+782)

0.8906903187277433

In [72]:
# Accuracy=0.8906903187277433

DECISION TREE

In [36]:
from sklearn.tree import DecisionTreeClassifier

In [37]:
DecTree=DecisionTreeClassifier()

In [38]:
DecTreemodel=DecTree.fit(X,y)

In [39]:
DecTreemodel.score(X,y)

1.0

In [40]:
DecTreepredict=DecTreemodel.predict(X)

In [48]:
DecTreepredict

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [49]:
pd.crosstab(bankdatadf.y,DecTreepredict)

col_0      0     1
y                 
0      39922     0
1          0  5289

In [73]:
# Accuracy=1

RANDOM FORESTS

In [42]:
from sklearn.ensemble import RandomForestClassifier

In [43]:
RF=RandomForestClassifier(n_estimators=1000)

In [44]:
RFmodel=RF.fit(X,y)

In [45]:
RFmodel.score(X,y)

1.0

In [46]:
RFpredict=RFmodel.predict(X)

In [47]:
RFresidual=y-RFpredict

In [51]:
pd.crosstab(bankdatadf.y,RFpredict)

col_0      0     1
y                 
0      39922     0
1          0  5289

In [74]:
# Accuracy=1

GRADIENT BOOSTING CLASSIFIER

In [52]:
from sklearn.ensemble import GradientBoostingClassifier

In [54]:
GB=GradientBoostingClassifier(n_estimators=1000)

In [56]:
GBmodel=GB.fit(X,y)

In [57]:
GBmodel.score(X,y)

0.93238371192851299

In [58]:
GBpredict=GBmodel.predict(X)

In [60]:
GBresidual=y-GBpredict

In [61]:
np.sqrt(np.mean(GBresidual**2))

0.26003132132781048

In [65]:
pd.crosstab(bankdatadf.y,GBpredict)

col_0      0     1
y                 
0      39125   797
1       2260  3029

In [76]:
(39125+3029)/(2260+797+39125+3029)

0.932383711928513

In [77]:
# Accuracy=0.932383711928513

NEURAL NETWORKS

In [62]:
from sklearn.neural_network import MLPClassifier

In [64]:
NN=MLPClassifier(activation='logistic',hidden_layer_sizes=(200,100,))

In [66]:
NNmodel=NN.fit(X,y)

In [67]:
NNmodel.score(X,y)

0.88911990444803257

In [68]:
NNpredict=NNmodel.predict(X)

In [70]:
pd.crosstab(bankdatadf.y,NNpredict)

col_0      0     1
y                 
0      39168   754
1       4259  1030

In [78]:
(39168+1030)/(39168+1030+754+4259)

0.8891199044480326

In [79]:
# Accuracy=0.8891199044480326

HYPOTHESIS TESTS

In [80]:
from scipy import stats as st

Chi-square test for y and Job:

In [82]:
st.chi2_contingency(pd.crosstab(bankdatadf.y,bankdata.job))

(836.10548774719655,
 3.3371219449355017e-172,
 11,
 array([[ 4566.0715755 ,  8593.5038818 ,  1313.04359559,  1094.93884232,
          8351.55771825,  1999.14640242,  1394.28099356,  3668.04512176,
           828.2682533 ,  6708.26643958,  1150.56879963,   254.30837628],
        [  604.9284245 ,  1138.4961182 ,   173.95640441,   145.06115768,
          1106.44228175,   264.85359758,   184.71900644,   485.95487824,
           109.7317467 ,   888.73356042,   152.43120037,    33.69162372]]))

In [83]:
# Since the p-value is less than 0.05, Reject NULL Hypothesis
# Statistically Significant

T test for y and Balance:

In [85]:
bankdata.y.describe()

count     45211
unique        2
top          no
freq      39922
Name: y, dtype: object

In [99]:
yes=bankdata[bankdata.y=='yes']
no=bankdata[bankdata.y=='no']

In [100]:
st.ttest_ind(yes.balance,no.balance)

Ttest_indResult(statistic=11.25043445878562, pvalue=2.5211136918751468e-29)

In [101]:
# Since the p-value is less than 0.05, Reject NULL Hypothesis
# Statistically Significant